require "pdf-reader"
require "bigdecimal"

# Parses body composition PDF reports generated by InBody devices and exported
# via the mynutri platform ("Powered by mynutri" footer on the report).
#
# Unlike the CSV export (see InbodyCsvParser), the PDF only reliably yields a
# single measurement: the current reading at the top of the report. The
# "Histórico da Composição Corporal" chart further down shows past readings,
# but those are rounded to whole numbers and have no exact date per point, so
# they are intentionally not imported.
class MynutriPdfParser
  DATE_TIME_REGEX      = %r{(\d{2})/(\d{2})/(\d{4})\s*às\s*\d{2}:\d{2}}
  WEIGHT_REGEX         = /Peso\s*\(kg\)\s+(\d+(?:\.\d+)?)\s*\(\s*\d+(?:\.\d+)?\s*~\s*\d+(?:\.\d+)?\s*\)/
  MUSCLE_MASS_REGEX    = /Esquelética\s*\(kg\)\s+(\d+(?:\.\d+)?)/
  FAT_PERCENTAGE_REGEX = /Percentual de Gordura\s+(\d+(?:\.\d+)?)/
  BMI_REGEX            = /Índice de Massa Corporal\s+(\d+(?:\.\d+)?)/
  VISCERAL_FAT_REGEX   = /Nível de Gordura Visceral\s+(\d+(?:\.\d+)?)\s*\(/

  ParsedRow = InbodyCsvParser::ParsedRow

  def self.pdf_format?(raw_content)
    raw_content.byteslice(0, 5) == "%PDF-"
  end

  # Returns an array with a single ParsedRow, or nil if the PDF can't be read
  # or isn't recognized as an InBody/mynutri report.
  def self.parse(raw_content)
    text = extract_text(raw_content)
    return nil if text.blank?

    date   = parse_date(text)
    weight = extract_decimal(text, WEIGHT_REGEX)
    return nil unless date && weight

    [
      ParsedRow.new(
        measured_on:    date,
        weight_kg:      weight,
        muscle_mass_kg: extract_decimal(text, MUSCLE_MASS_REGEX),
        fat_percentage: extract_decimal(text, FAT_PERCENTAGE_REGEX),
        bmi:            extract_decimal(text, BMI_REGEX),
        visceral_fat:   extract_decimal(text, VISCERAL_FAT_REGEX)
      )
    ]
  rescue PDF::Reader::MalformedPDFError, PDF::Reader::UnsupportedFeatureError
    nil
  end

  private_class_method def self.extract_text(raw_content)
    reader = PDF::Reader.new(StringIO.new(raw_content))
    reader.pages.map(&:text).join("\n")
  end

  private_class_method def self.parse_date(text)
    match = text.match(DATE_TIME_REGEX)
    return nil unless match

    Date.new(match[3].to_i, match[2].to_i, match[1].to_i)
  rescue ArgumentError
    nil
  end

  private_class_method def self.extract_decimal(text, regex)
    match = text.match(regex)
    return nil unless match

    BigDecimal(match[1])
  end
end
